### PR TITLE
Add function to identify if port exists in a cell

### PR DESCRIPTION
**Pull request by oliveira-mauricio**

### CODE REVIEW

**Comment by prusse-martin** [comment]
I guess I need to check my e-mail settings. I missed the e-mail about the master breaking.

**Comment by nicoddemus** [comment]
The build is failing though... do we need `pytest_rerunfailures`?

**Comment by nicoddemus** [comment]
Can you remove `pytest-rerunfailures` first @oliveira-mauricio?

**Comment by nicoddemus** [comment]
Hmmm actually hold on

**Comment by prusse-martin** [comment]
> 
> 
> The build is failing though... do we need `pytest_rerunfailures`?

```
INTERNALERROR>   File "/home/travis/miniconda/envs/qmxgraph/lib/python3.6/site-packages/pytest_rerunfailures.py", line 135, in _remove_cached_results_from_failed_fixtures
INTERNALERROR>     result, cache_key, err = getattr(fixture_def, cached_result)
INTERNALERROR> TypeError: 'NoneType' object is not iterable
```

It looks some problem with `pytest_rerunfailures` it self.
BTW the master branch is also failing with this.

**Comment by nicoddemus** [comment]
Yep, the problem is that we should be using `pytest-rerunfailures` 9.0:

https://github.com/pytest-dev/pytest-rerunfailures/blob/master/CHANGES.rst#90-2020-03-18

And indeed it is not available on conda-forge:

https://anaconda.org/conda-forge/pytest-rerunfailures/files

Which is stalled because nobody merged yet:

https://github.com/conda-forge/pytest-rerunfailures-feedstock/pull/2

I will ping someone with powers on conda-forge to help here.

**Comment by nicoddemus** [comment]
Argh that PR needs updating (even though it is ready for merging)... I will work on it after my meetings.

**Comment by nicoddemus** [comment]
https://github.com/conda-forge/pytest-rerunfailures-feedstock/pull/3

**Comment by nicoddemus** [comment]
9.0 was released: https://anaconda.org/conda-forge/pytest-rerunfailures/files

Please trigger the build again 👍

**Pull request merged**
