### PR TITLE
dump/restore methods exposing writeGraphModel/readGraphModel

### PR DESCRIPTION
**Pull request by prusse-martin**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Waiting for @fogo to give his blessing. 👍

**Comment by prusse-martin** [comment]
Did the lint fix.
The coverage got down since the 2 functions added are being tested only using selenium to check the actual javascript implementation. Do you think it is worth to have a test covering the wrapper functions in `api.py`?

**Comment by nicoddemus** [comment]
Let's see what @fogo has to say about it.

**Comment by fogo** [comment]
The new feature seems fine. It seems this is the expected way to store/restore a mxGraph. Just take on future changes to make sure they are always compatible with this (i.e. they are visually identical after restored).

About the coverage on API, this is already a problem actually. If you take a deeper look, you'll notice that there're other methods uncovered. I guess it is time to decide to either cover them (more work, safer) all or maybe just don't cover it at all (risky, API isn't always straightforward between Python/Qt/JS).

**Comment by prusse-martin** [comment]
Sorry for delaying the comment.
@nicoddemus think it is better to have coverage on this and I kind agree with him.
He suggested at least have tests mocking the actual javascript functions so just "API" is tested (the actual javascript is already tested).

I can add that later. If you think mocking is good enough I plan to use [testdouble.js](https://github.com/testdouble/testdouble.js) or [Sinon.JS](http://sinonjs.org/).

**Comment by fogo** [comment]
Sorry for the late answer, but mocking feels like a good start. I look forward to the future PR ;)

**Pull request merged**
